server:
  port: 9003
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: EMPLOYEE-SERVICE
          uri: http://localhost:9004/employess
          predicates:
            - Path=/employees/**
        - id: CUSTOMER-SERVICE
          uri: http://localhost:9005/customers/
          predicates:
            - Path=/customers/**
        - id: PRODUCT-SERVICE
          uri: http://localhost:9002/products/
          predicates:
            - Path=/products/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost